### ISSUE TITLE
I can't upload the firmware to the arduino Nano

### ISSUE THREAD

**Issue by Dusty37** [JakeS0ft/STREAM#1]
Greetings Congratulations to the program thank you very much for everyone to be free
My question is using the following windows 10
but for some reason I can't upload the firmware to the arduino Nano
Arduini IDE works on nano FX Saber Os I can install
but I did not do all the instructions in STREAM as it is written but I don't know how to put it on Nano

**Comment by JakeS0ft** [comment]
Were you sure to set the baud rate to 57600 in the installer?

If that doesn't work, you can try uploading manually from outside the GUI using the **UploadFirmware.bat** file. You can edit this script to use the correct COM port and observe any error messages that might otherwise be hidden. There are instructions at the top of the file that explain how to use the script.

**Comment by JakeS0ft** [comment]
Since no feedback in several months, assuming the suggested fix worked. Closing this issue.
