### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by jjloy314** [JakeS0ft/STREAM#2]
Hi-  I'm having trouble getting up and running, I'm hoping you can please help.  I'm using a brewboard with neopixel, Nano clone. 

I cannot get STREAM to handshake with the board to start the GUI.

I can successfully install via STREAM.jar and UplaodFirmware.bat.  However, launching the GUI always throws: Handshake failed.

I can also successfully upload sketches via Arduino, for what it's worth.

I've tried the CH340/CH341 driver update with no luck.  

Can you think of anything I can try?  Any help would be appreciated.

**Comment by JakeS0ft** [comment]
If your saber is otherwise working but you can't connect to the GUI, ensure that you hold in the main activation button until you hear "STREAM Mode" voice prompt. Do this *after* you hit the "connect" button on the GUI. There are detailed instructions in the user guide. 

I've had a few people report this issue and it turned out that they were letting off the button when they hear "Menu Mode", but that's too soon. You have to keep holding the button until you hear "STREAM Mode".

Hope that helps.

**Comment by jjloy314** [comment]
Thank you for the clarification.  I misunderstood the directions.  Feel free to remove this issue.
