### ISSUE TITLE
Handshake failed 

### ISSUE THREAD

**Issue by ozzyrivera09** [JakeS0ft/STREAM#4]
I cant connect. I just keep getting this error

**Comment by JakeS0ft** [comment]
Try following the instructions *exactly* as described in the "Starting a Session" section of the user guide . 
https://github.com/JakeS0ft/STREAM/blob/master/doc/UserGuide.pdf

When this error is reported, it's usually because the saber is not in *STREAM Mode*. After pressing *Connect* button on the GUI, you have to then press and hold the saber's main activation button until "STREAM Mode" is announced. Do NOT let of the button when you hear "Menu Mode", keep holding it until you hear "STREAM Mode" voice prompt. 

Thank you for trying STREAM!

**Comment by JakeS0ft** [comment]
Since the same user later implied this issue was resolved when posting issue #5 (https://github.com/JakeS0ft/STREAM/issues/5), assuming the suggested fix worked. Closing this issue.
